### ISSUE TITLE
  pod 'react-native-baidu-map-jm', :podspec => '../node_modules/react-native-baidu-map-jm/ios/react-native-baidu-map-jm.podspec' is error

### ISSUE THREAD

**Issue by liuyunqiang** [Eafy/react-native-baidu-map-jm#1]

**Comment by liuyunqiang** [comment]
pod 'react-native-baidu-map-jm', :podspec => '../node_modules/react-native-baidu-map-jm/react-native-baidu-map-jm.podspec'

**Comment by Eafy** [comment]
> pod 'react-native-baidu-map-jm', :podspec => '../node_modules/react-native-baidu-map-jm/react-native-baidu-map-jm.podspec'

如果你的PodFile文件和node_modules文件夹目录同级，PodFile文件中需要写成：pod 'react-native-baidu-map-jm', :podspec => './node_modules/react-native-baidu-map-jm/react-native-baidu-map-jm.podspec'
PS：podspec =>''后面是podsped文件路径
