### ISSUE TITLE
Execution failed for task ':react-native-baidu-map-jm:compileDebugJavaWithJavac'

### ISSUE THREAD

**Issue by liuyunqiang** [Eafy/react-native-baidu-map-jm#2]
![屏幕快照 2019-09-17 下午6 16 02](https://user-images.githubusercontent.com/17231906/65033292-472d5680-d977-11e9-9989-3571c1de76ea.png)
![屏幕快照 2019-09-17 下午6 16 22](https://user-images.githubusercontent.com/17231906/65033299-48f71a00-d977-11e9-8848-9c3e90b1fb39.png)
还有个问题  我android 按照你文档更改   运行报了这个错  这是问什么 请大神指教！

**Comment by Eafy** [comment]
1、先查下build.gradle文件中的库依赖，如果是这样的：
<img width="433" alt="图片" src="https://user-images.githubusercontent.com/12604160/65034236-35e54980-d979-11e9-94f4-f788ad7ee1aa.png">
把上一句的依赖屏蔽，打开下一句的依赖（因为这个地方我个人项目引入了App中的百度地图的库，所以并没有使用RN项目中的库）；

2、如果第1种还没有解决，查看下自己工程是否包含了2份百度地图的库，修改只引用其中一个，如只用了RN项目中的百度地图，修改下MapListener.java文件，里面有2句屏蔽的接口需要打开，因为个人项目中百度地图版本不一样导致它的接口不一样。

**Comment by Eafy** [comment]
MapListener.java文件中的下面代码需要打开，监听接口复用少些了下面这个接口：
<img width="596" alt="图片" src="https://user-images.githubusercontent.com/12604160/65034546-d9365e80-d979-11e9-91f3-8cae842aea2f.png">

**Comment by Eafy** [comment]
MapListener.java文件中的下面代码需要打开，监听接口复用少些了下面这个接口：
<img width="598" alt="图片" src="https://user-images.githubusercontent.com/12604160/65034629-008d2b80-d97a-11e9-9088-9cf9994f8727.png">
